// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBJO9CoNWWY6SXVgBZBSjPuAvZ6Y3TVdU',
    appId: '1:809264708215:web:f11ef63a9af8018b0ce472',
    messagingSenderId: '809264708215',
    projectId: 'appthuetho',
    authDomain: 'appthuetho.firebaseapp.com',
    storageBucket: 'appthuetho.firebasestorage.app',
    measurementId: 'G-Q61X0RF75H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcs6M0OdlyJWsMa_xtc5GIs7FGNprPl0',
    appId: '1:809264708215:android:3b63fad10681616d0ce472',
    messagingSenderId: '809264708215',
    projectId: 'appthuetho',
    storageBucket: 'appthuetho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIRJAV8nTm2qlgtsFGrkfe68pSZ483aEs',
    appId: '1:809264708215:ios:693a82b72299aa730ce472',
    messagingSenderId: '809264708215',
    projectId: 'appthuetho',
    storageBucket: 'appthuetho.firebasestorage.app',
    iosBundleId: 'com.example.appthuetho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIRJAV8nTm2qlgtsFGrkfe68pSZ483aEs',
    appId: '1:809264708215:ios:693a82b72299aa730ce472',
    messagingSenderId: '809264708215',
    projectId: 'appthuetho',
    storageBucket: 'appthuetho.firebasestorage.app',
    iosBundleId: 'com.example.appthuetho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBJO9CoNWWY6SXVgBZBSjPuAvZ6Y3TVdU',
    appId: '1:809264708215:web:22d6782d2d63d6940ce472',
    messagingSenderId: '809264708215',
    projectId: 'appthuetho',
    authDomain: 'appthuetho.firebaseapp.com',
    storageBucket: 'appthuetho.firebasestorage.app',
    measurementId: 'G-Y01Y8RNY89',
  );
}
